name: Publish NPM Package

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - id: cache-dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build
      - run: npm publish --tag canary
        if: github.event.release.prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish
        if: "!github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
